# Generated by Django 3.2.7 on 2021-09-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_postmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='subtitle',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
