# Generated by Django 3.2.7 on 2021-09-20 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_aboutmodel_background_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=140)),
                ('text', models.TextField(blank=True, max_length=150, null=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='blog_images')),
            ],
        ),
    ]
