# Generated by Django 3.2.7 on 2021-09-20 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_contactmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmodel',
            name='background_image',
        ),
    ]
