# Generated by Django 3.2.7 on 2021-09-22 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_remove_contactmodel_background_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='blog_images')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.postmodel')),
            ],
        ),
    ]
