# Generated by Django 3.2.7 on 2021-09-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_postimagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
